site_name: Avera G-60 Electric Guitar
site_author: Orion Miller
site_description: "Avera G-60 electric guitar design"

theme: #for configuration see https://squidfunk.github.io/mkdocs-material/setup/
  name: material
  custom_dir: overrides  
  palette:
    scheme: slate
    primary: black
    accent: teal
  logo: images/S_Avera_Logo7.png
  favicon: images/favicon.ico
  font:
    text: PT Sans  
  features:
    - navigation.tabs  
    # - navigation.tabs.sticky 
    - navigation.top    
    - navigation.indexes 
    - toc.integrate
    - navigation.instant
    - navigation.instant.progress    

# repo_url: https://github.com/orion-miller/Avera_G60_Website #adds link to repo in header

nav:
- 'About': 
  - 'About': 'index.md'
  - 'Specs': 'specs.md'
  - 'Controls': 'controls.md'
- 'Build Process': 'build_process.md'
- "Download Files": 'download.md'
- 'Image Gallery': 'image_gallery.md'
# - 'Discussion': 'discussion.md'    

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:orion.miller@outlook.com    
    - icon: fontawesome/brands/github
      link: https://github.com/orion-miller        
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/orionmmiller/   
  generator: false #takes away made with mkdocs message (takes up an extra line) - can add back inline if want to keep it  
  # disqus: orionmiller  
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX         

copyright: '&copy; 2023-2025 Orion Miller'

#to serve locally, go to this dir in command prompt and enter "mkdocs serve"
