site_name: Avera G-60 Electric Guitar
theme: 
  name: material
  palette:
    scheme: slate
    primary: black
  favicon: images/favicon.ico
  font:
    text: PT Sans  
  features:
    - navigation.tabs    

repo_url: https://github.com/orion-miller/Avera_G60_Website
site_author: Orion Miller
site_description: "Avera G-60 electric guitar design"

nav:
- 'About': 'about.md'
- 'Specs': 
  - 'Specs': 'specs.md'
  - 'Controls': 'controls.md'
- 'Image Gallery': 'image_gallery.md'
- "Download": 'download.md'
- 'Discussion': 'discussion.md'    

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/orionmmiller/   

copyright: Copyright &copy; 2023 Orion Miller